### ISSUE TITLE
TPU

### ISSUE THREAD

**Issue by wimjan123** [Lightning-AI/lit-llama#102]
Does this code work on TPU?

**Comment by lantiga** [comment]
We haven’t tried this particular model yet but we will soon.

Fabric supports TPUs, just set accelerator=“tpu” when instantiating the Fabric object

**Comment by lantiga** [comment]
As an update, we'll be opening a long-running branch for `tpu` support in the next few days. A number of TPU support-related PRs are landing on the main lightning repo.

**Comment by winglian** [comment]
I got about this far but sort of hit a brick wall when fine-tuning: https://github.com/Lightning-AI/lit-llama/compare/main...winglian:lit-llama:tpu?expand=1

```
:$ PT_XLA_DEBUG=1 python3 finetune_lora.py --checkpoint_path ../data/lit-llama/13B/state_dict.pth --out_path ../data/alpaca-lora --model_size 13B --tokenizer_model_path ../data/lit-llama/tokenizer.model --dataset_path ../data/alpaca
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/connector.py:443: UserWarning: You passed `Fabric(accelerator='tpu', precision='16-mixed')` but AMP with fp16 is not supported with TPUs. Using `precision='bf16-mixed'` instead.
  rank_zero_warn(
Global seed set to 1337
Global seed set to 1338
Global seed set to 1339
Global seed set to 1341
Global seed set to 1340
Global seed set to 1343
Global seed set to 1342
Global seed set to 1344
finetune_lora.py:198: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input_ids = [torch.tensor(data[i]["input_ids"], dtype=torch.int64) for i in ix]
finetune_lora.py:199: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = [torch.tensor(data[i]["labels"], dtype=torch.int64) for i in ix]
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x7ffef85720c0 
https://symbolize.stripped_domain/r/?trace=7f90d926a00b,7f90d926a08f,ffffffffdce3ffff,e900000002bffe88&map= 
*** SIGABRT received by PID 40552 (TID 40552) on cpu 63 from PID 40552; stack trace: ***
PC: @     0x7f90d926a00b  (unknown)  raise
    @     0x7f8f85d71a1a       1152  (unknown)
    @     0x7f90d926a090  115675232  (unknown)
    @ 0xffffffffdce40000  (unknown)  (unknown)
    @ 0xe900000002bffe89  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f90d926a00b,7f8f85d71a19,7f90d926a08f,ffffffffdce3ffff,e900000002bffe88&map=ceee8fa20ddf9c34af43f587221e91de:7f8f78e49000-7f8f85f88840 
E0411 20:31:38.481648   40552 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0411 20:31:38.481670   40552 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0411 20:31:38.481692   40552 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0411 20:31:38.481699   40552 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0411 20:31:38.497379   40552 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0411 20:31:38.497441   40552 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0411 20:31:38.497448   40552 coredump_hook.cc:580] RAW: Dumping core locally.
E0411 20:31:39.111086   40552 process_state.cc:784] RAW: Raising signal 6 with default behavior
iter_num: 0
finetune_lora.py:202: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input_ids = [torch.tensor(data[i]["input_ids"], dtype=torch.int64) for i in ix]
finetune_lora.py:203: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = [torch.tensor(data[i]["labels"], dtype=torch.int64) for i in ix]
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x7ffd34ae75c0 
https://symbolize.stripped_domain/r/?trace=7f57e93be00b,7f57e93be08f,ffffffffdcd2ffff,e900000002bffe88&map= 
*** SIGABRT received by PID 50662 (TID 50662) on cpu 9 from PID 50662; stack trace: ***
PC: @     0x7f57e93be00b  (unknown)  raise
    @     0x7f5695ec5a1a       1152  (unknown)
    @     0x7f57e93be090  113201248  (unknown)
    @ 0xffffffffdcd30000  (unknown)  (unknown)
    @ 0xe900000002bffe89  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f57e93be00b,7f5695ec5a19,7f57e93be08f,ffffffffdcd2ffff,e900000002bffe88&map=ceee8fa20ddf9c34af43f587221e91de:7f5688f9d000-7f56960dc840 
E0411 21:38:00.021702   50662 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0411 21:38:00.021727   50662 coredump_hook.cc:453] RAW: Skipping coredump since rlimit was 0 at process start.
E0411 21:38:00.021738   50662 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0411 21:38:00.021746   50662 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0411 21:38:00.021757   50662 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0411 21:38:00.021776   50662 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0411 21:38:00.021784   50662 coredump_hook.cc:580] RAW: Dumping core locally.
E0411 21:38:00.642134   50662 process_state.cc:784] RAW: Raising signal 6 with default behavior
2023-04-11 21:38:07.054397: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1681249087.054152683","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:07.054402: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Socket closed" and grpc_error_string = "{"created":"@1681249087.054089407","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:07.054404: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1681249087.054098295","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:07.054409: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1681249087.054073941","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:07.054429: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Socket closed" and grpc_error_string = "{"created":"@1681249087.054213384","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:07.054683: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Socket closed" and grpc_error_string = "{"created":"@1681249087.054106785","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2023-04-11 21:38:09.318793: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1681249089.318534483","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
Traceback (most recent call last):
  File "finetune_lora.py", line 230, in <module>
    CLI(main)
  File "/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "finetune_lora.py", line 65, in main
    fabric.launch(run_training)
  File "/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py", line 650, in launch
    return self._strategy.launcher.launch(function, *args, **kwargs)
  File "/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py", line 70, in launch
    xmp.spawn(
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 397, in spawn
    result = torch.multiprocessing.start_processes(
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGABRT
WARNING:pt-xla-profiler:================================================================================
WARNING:pt-xla-profiler:Unlowered Op usage summary (more of these ops, lower performance)
WARNING:pt-xla-profiler:Note: _local_scalar_dense typically indicates CPU context access
WARNING:pt-xla-profiler:--------------------------------------------------------------------------------
WARNING:pt-xla-profiler:FRAME (count=323):
WARNING:pt-xla-profiler:Unlowered Op: "xla_cpu_fallback"
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:FRAME (count=320):
WARNING:pt-xla-profiler:  __torch_function__ (/usr/local/lib/python3.8/dist-packages/torch/utils/_device.py:62)
WARNING:pt-xla-profiler:  __init__ (/home/wing/workspace/lit-llama/lit_llama/lora.py:73)
WARNING:pt-xla-profiler:  __init__ (/home/wing/workspace/lit-llama/lit_llama/lora.py:198)
WARNING:pt-xla-profiler:  __init__ (/home/wing/workspace/lit-llama/lit_llama/model.py:84)
WARNING:pt-xla-profiler:  <listcomp> (/home/wing/workspace/lit-llama/lit_llama/model.py:47)
WARNING:pt-xla-profiler:  __init__ (/home/wing/workspace/lit-llama/lit_llama/model.py:47)
WARNING:pt-xla-profiler:  run_training (finetune_lora.py:83)
WARNING:pt-xla-profiler:  _run_with_setup (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:741)
WARNING:pt-xla-profiler:  _wrapping_function (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:89)
WARNING:pt-xla-profiler:  _start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:328)
WARNING:pt-xla-profiler:  _mp_start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:334)
WARNING:pt-xla-profiler:  _wrap (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:69)
WARNING:pt-xla-profiler:  run (/usr/lib/python3.8/multiprocessing/process.py:108)
WARNING:pt-xla-profiler:  _bootstrap (/usr/lib/python3.8/multiprocessing/process.py:315)
WARNING:pt-xla-profiler:  _launch (/usr/lib/python3.8/multiprocessing/popen_fork.py:75)
WARNING:pt-xla-profiler:  __init__ (/usr/lib/python3.8/multiprocessing/popen_fork.py:19)
WARNING:pt-xla-profiler:  _Popen (/usr/lib/python3.8/multiprocessing/context.py:277)
WARNING:pt-xla-profiler:  start (/usr/lib/python3.8/multiprocessing/process.py:121)
WARNING:pt-xla-profiler:  start_processes (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:188)
WARNING:pt-xla-profiler:  spawn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:397)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:70)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:650)
WARNING:pt-xla-profiler:  main (finetune_lora.py:65)
WARNING:pt-xla-profiler:  _run_component (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:138)
WARNING:pt-xla-profiler:  CLI (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:82)
WARNING:pt-xla-profiler:  <module> (finetune_lora.py:230)
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:FRAME (count=1):
WARNING:pt-xla-profiler:  zero_pad (/home/wing/workspace/lit-llama/lit_llama/lora.py:89)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/lora.py:138)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:113)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:89)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:68)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/wrappers.py:110)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  train (finetune_lora.py:122)
WARNING:pt-xla-profiler:  run_training (finetune_lora.py:92)
WARNING:pt-xla-profiler:  _run_with_setup (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:741)
WARNING:pt-xla-profiler:  _wrapping_function (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:89)
WARNING:pt-xla-profiler:  _start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:328)
WARNING:pt-xla-profiler:  _mp_start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:334)
WARNING:pt-xla-profiler:  _wrap (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:69)
WARNING:pt-xla-profiler:  run (/usr/lib/python3.8/multiprocessing/process.py:108)
WARNING:pt-xla-profiler:  _bootstrap (/usr/lib/python3.8/multiprocessing/process.py:315)
WARNING:pt-xla-profiler:  _launch (/usr/lib/python3.8/multiprocessing/popen_fork.py:75)
WARNING:pt-xla-profiler:  __init__ (/usr/lib/python3.8/multiprocessing/popen_fork.py:19)
WARNING:pt-xla-profiler:  _Popen (/usr/lib/python3.8/multiprocessing/context.py:277)
WARNING:pt-xla-profiler:  start (/usr/lib/python3.8/multiprocessing/process.py:121)
WARNING:pt-xla-profiler:  start_processes (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:188)
WARNING:pt-xla-profiler:  spawn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:397)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:70)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:650)
WARNING:pt-xla-profiler:  main (finetune_lora.py:65)
WARNING:pt-xla-profiler:  _run_component (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:138)
WARNING:pt-xla-profiler:  CLI (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:82)
WARNING:pt-xla-profiler:  <module> (finetune_lora.py:230)
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:FRAME (count=1):
WARNING:pt-xla-profiler:  build_rope_cache (/home/wing/workspace/lit-llama/lit_llama/model.py:217)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:122)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:89)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:68)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/wrappers.py:110)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  train (finetune_lora.py:122)
WARNING:pt-xla-profiler:  run_training (finetune_lora.py:92)
WARNING:pt-xla-profiler:  _run_with_setup (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:741)
WARNING:pt-xla-profiler:  _wrapping_function (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:89)
WARNING:pt-xla-profiler:  _start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:328)
WARNING:pt-xla-profiler:  _mp_start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:334)
WARNING:pt-xla-profiler:  _wrap (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:69)
WARNING:pt-xla-profiler:  run (/usr/lib/python3.8/multiprocessing/process.py:108)
WARNING:pt-xla-profiler:  _bootstrap (/usr/lib/python3.8/multiprocessing/process.py:315)
WARNING:pt-xla-profiler:  _launch (/usr/lib/python3.8/multiprocessing/popen_fork.py:75)
WARNING:pt-xla-profiler:  __init__ (/usr/lib/python3.8/multiprocessing/popen_fork.py:19)
WARNING:pt-xla-profiler:  _Popen (/usr/lib/python3.8/multiprocessing/context.py:277)
WARNING:pt-xla-profiler:  start (/usr/lib/python3.8/multiprocessing/process.py:121)
WARNING:pt-xla-profiler:  start_processes (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:188)
WARNING:pt-xla-profiler:  spawn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:397)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:70)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:650)
WARNING:pt-xla-profiler:  main (finetune_lora.py:65)
WARNING:pt-xla-profiler:  _run_component (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:138)
WARNING:pt-xla-profiler:  CLI (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:82)
WARNING:pt-xla-profiler:  <module> (finetune_lora.py:230)
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:FRAME (count=1):
WARNING:pt-xla-profiler:  apply_rope (/home/wing/workspace/lit-llama/lit_llama/model.py:231)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:129)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:89)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/workspace/lit-llama/lit_llama/model.py:68)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  forward (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/wrappers.py:110)
WARNING:pt-xla-profiler:  _call_impl (/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501)
WARNING:pt-xla-profiler:  train (finetune_lora.py:122)
WARNING:pt-xla-profiler:  run_training (finetune_lora.py:92)
WARNING:pt-xla-profiler:  _run_with_setup (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:741)
WARNING:pt-xla-profiler:  _wrapping_function (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:89)
WARNING:pt-xla-profiler:  _start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:328)
WARNING:pt-xla-profiler:  _mp_start_fn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:334)
WARNING:pt-xla-profiler:  _wrap (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:69)
WARNING:pt-xla-profiler:  run (/usr/lib/python3.8/multiprocessing/process.py:108)
WARNING:pt-xla-profiler:  _bootstrap (/usr/lib/python3.8/multiprocessing/process.py:315)
WARNING:pt-xla-profiler:  _launch (/usr/lib/python3.8/multiprocessing/popen_fork.py:75)
WARNING:pt-xla-profiler:  __init__ (/usr/lib/python3.8/multiprocessing/popen_fork.py:19)
WARNING:pt-xla-profiler:  _Popen (/usr/lib/python3.8/multiprocessing/context.py:277)
WARNING:pt-xla-profiler:  start (/usr/lib/python3.8/multiprocessing/process.py:121)
WARNING:pt-xla-profiler:  start_processes (/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py:188)
WARNING:pt-xla-profiler:  spawn (/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py:397)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/strategies/launchers/xla.py:70)
WARNING:pt-xla-profiler:  launch (/home/wing/.local/lib/python3.8/site-packages/lightning/fabric/fabric.py:650)
WARNING:pt-xla-profiler:  main (finetune_lora.py:65)
WARNING:pt-xla-profiler:  _run_component (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:138)
WARNING:pt-xla-profiler:  CLI (/home/wing/.local/lib/python3.8/site-packages/jsonargparse/cli.py:82)
WARNING:pt-xla-profiler:  <module> (finetune_lora.py:230)
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:
WARNING:pt-xla-profiler:================================================================================

```

**Comment by lantiga** [comment]
very interesting, thanks @winglian!
this was on what TPU version?

/cc @carmocca

**Comment by winglian** [comment]
GCP v3-8 TPUs. Thanks!

**Comment by carmocca** [comment]
THis is great @winglian. We're working on supporting XLA's new PJRT runtime (https://pytorch.org/blog/pytorch-2.0-xla/#pjrt-runtime-beta) with Lightning and will try it on this repository asap. We'll keep this updated

**Comment by lantiga** [comment]
TPU support is in! 🎉

**Comment by carmocca** [comment]
Re-opening as the training/finetuning scripts are not updated yet

**Comment by lantiga** [comment]
You're right :-)

**Comment by gkroiz** [comment]
Should the `tpu-inference` branch also include the TPU updates for training and finetuning scripts?

**Comment by carmocca** [comment]
Yes, they need to be updated. Feel free to open PRs for them. It doesn't need to be on that specific branch

**Comment by gkroiz** [comment]
I did not test the inference script, but from messing around with the pretraining script there are at least two causes for the unlowered ops warnings in https://github.com/Lightning-AI/lit-llama/issues/102#issuecomment-1504427550.
1) there is a separate rendezvous() function when using PJRT and XRT. A slight adjustment needs to be made in the [Pytorch XLA repository](https://github.com/pytorch/xla/blob/4020f55b3a65e5fab7857da56f9d4f4be3400fe5/torch_xla/core/xla_model.py#L986), I can link the PR when it is ready.
2) cross_entropy() is not currently supported by PT XLA and therefore runs into the Unlowered Ops warning. Maybe in the meantime we switch to a loss function that is included [here](https://github.com/pytorch/xla/blob/master/codegen/xla_native_functions.yaml)?

cc @Liyang90

**Comment by Liyang90** [comment]
> cross_entropy() is not currently supported by PT XLA and therefore runs into the Unlowered Ops warning. 

The cross_entropy() can be replaced with softmax and nll loss if that's the case.

**Comment by gkroiz** [comment]
> I did not test the inference script, but from messing around with the pretraining script there are at least two causes for the unlowered ops warnings in [#102 (comment)](https://github.com/Lightning-AI/lit-llama/issues/102#issuecomment-1504427550).
> 
> 1. there is a separate rendezvous() function when using PJRT and XRT. A slight adjustment needs to be made in the [Pytorch XLA repository](https://github.com/pytorch/xla/blob/4020f55b3a65e5fab7857da56f9d4f4be3400fe5/torch_xla/core/xla_model.py#L986), I can link the PR when it is ready.
> 2. cross_entropy() is not currently supported by PT XLA and therefore runs into the Unlowered Ops warning. Maybe in the meantime we switch to a loss function that is included [here](https://github.com/pytorch/xla/blob/master/codegen/xla_native_functions.yaml)?
> 
> cc @Liyang90

Upon further review the real culprit for the unlowered ops in (2) is calling `loss.item()`. Without printing `loss.item()`, `cross_entropy()` does not trigger the unlowered ops warning. We can leave the loss function as is.

**Comment by carmocca** [comment]
Which `loss.item()` call exactly?

**Comment by gkroiz** [comment]
> Which `loss.item()` call exactly?

Here: https://github.com/Lightning-AI/lit-llama/blob/main/train_shakespeare.py#L119, although I would guess that the `loss.item()` in `validate()` would also trigger unlowered ops warnings

**Comment by gkroiz** [comment]
https://github.com/pytorch/xla/pull/4990 should address bullet 1 in https://github.com/Lightning-AI/lit-llama/issues/102#issuecomment-1530369715
