### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by heoyongun** [Lightning-AI/lit-llama#115]
$ python3 generate.py --quantize llm.int8 --prompt "Hello, my name is"

error message

ubuntu 22.04

```
Traceback (most recent call last):
  File "generate.py", line 159, in <module>
    CLI(main)
  File "/home/yongun/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/home/yongun/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "generate.py", line 104, in main
    assert checkpoint_path.is_file()
AssertionError
```

**Comment by awaelchli** [comment]
@heoyongun You need to download the weights first before you can run inference. You can follow the instructions in the README for this: https://github.com/Lightning-AI/lit-llama#use-the-model

**Comment by lantiga** [comment]
Closing this, feel free to reopen @heoyongun
