### ISSUE TITLE
No module named 'torch.utils._device'

### ISSUE THREAD

**Issue by nikuson** [Lightning-AI/lit-llama#135]
No module named 'torch.utils._device'

**Comment by carmocca** [comment]
Can you share the complete error stacktrace?

Are you using `torch==2.0`?

**Comment by nikuson** [comment]
yes i am using torch 2.0

> Can you share the complete error stacktrace?
> 
> Are you using `torch==2.0`?

yes i am using torch 2.0

**Comment by nikuson** [comment]
> Can you share the complete error stacktrace?
> 
> Are you using `torch==2.0`?

Traceback (most recent call last):
  File "D:\Python\Llama\llama\generate.py", line 10, in <module>      
    from lit_llama.utils import EmptyInitOnDevice
  File "D:\Python\Llama\llama\lit_llama\utils.py", line 8, in <module>
    import torch.utils._device
ModuleNotFoundError: No module named 'torch.utils._device'

**Comment by carmocca** [comment]
Can you share the output of

`pip list | grep torch`
and
`python -c 'import torch; print(torch.__version__)'`?


You might have non-release version that doesn't include that file. Reinstalling torch by following the instructions at `pytorch.org` should help

**Comment by javadsadghei112** [comment]
No module named 'torch._utils'              how can i fix this eror

**Comment by Ramakrishna176420** [comment]
Traceback (most recent call last):
  File "sketch3.py", line 1, in <module>
    import torch
  File "/home/stud2201/.local/lib/python3.8/site-packages/torch/__init__.py", line 21, in <module>
    from ._utils import _import_dotted_name
ModuleNotFoundError: No module named 'torch._utils'
