### ISSUE TITLE
Huggingface checkpoint conversion script is not working!

### ISSUE THREAD

**Issue by rajeevbaalwan** [Lightning-AI/lit-llama#147]
@lantiga I have used the script again as mentioned in #70  and getting below error
```
python scripts/convert_hf_checkpoint.py --hf_checkpoint_path ../llama-7b-hf/
Initializing lit-llama
Processing pytorch_model-00022-of-00033.bin
Traceback (most recent call last):
  File "scripts/convert_hf_checkpoint.py", line 137, in <module>
    CLI(convert_hf_checkpoint)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "scripts/convert_hf_checkpoint.py", line 79, in convert_hf_checkpoint
    hf_weights = torch.load(os.path.join(hf_checkpoint_path, bin_file), map_location="cpu")
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/hdd1/rajeevy/anaconda3/envs/lama/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
Also as the files downloaded by below command does not contain actual checkpoint file, do I need to place checkpoint file in the same folder 
```
git clone https://huggingface.co/decapoda-research/llama-7b-hf
```

**Comment by lantiga** [comment]
Can you make sure you are cloning with `lfs` installed?

https://huggingface.co/docs/hub/models-downloading

Run `git lfs install` prior to cloning, or you'll only get placeholder files instead of the actual files.

**Comment by lantiga** [comment]
@rajeevbaalwan did the above solve it?

**Comment by carmocca** [comment]
I experienced the same error because `git lfs` wasn't installed.

#169 will fix the paper cuts here.
