### ISSUE TITLE
Training script: Only PyTorch DataLoader are currently supported in `setup_dataloaders`

### ISSUE THREAD

**Issue by LamMoh1** [Lightning-AI/lit-llama#233]
Hello, I'm facing this error with the red-pajama training script. 

```
Traceback (most recent call last):
  File ".../LLM/LLaMa/lit-llama/train_redpajama.py", line 312, in <module>
    CLI(main)
  File ".../.conda/envs/llm/lib/python3.9/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File ".../.conda/envs/llm/lib/python3.9/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File ".../LLaMa/lit-llama/train_redpajama.py", line 89, in main
    train_dataloader, val_dataloader = fabric.setup_dataloaders(train_dataloader, val_dataloader)
  File ".../.conda/envs/llm/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 308, in setup_dataloaders
    self._validate_setup_dataloaders(dataloaders)
  File ".../.conda/envs/llm/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 890, in _validate_setup_dataloaders
    raise TypeError("Only PyTorch DataLoader are currently supported in `setup_dataloaders`.")
TypeError: Only PyTorch DataLoader are currently supported in `setup_dataloaders`
```
I think the last update on the script caused this error (https://github.com/Lightning-AI/lit-llama/pull/213)

Thank you for providing the training script, it's very simple and neat. I really appreciate that.

**Comment by awaelchli** [comment]
Hey @LamMoh1 
Thanks for reporting. This is because the val_dir is None, and then the dataloader becomes None. I'm sorry for missing this in a last-minute change, I'll send a PR fixing this.

**Comment by LamMoh1** [comment]
Thank you!
