### ISSUE TITLE
Weight conversion/download for 7B checkpoint causing corruption error

### ISSUE THREAD

**Issue by momalekabid** [Lightning-AI/lit-llama#338]
after running this command to download the weights:

``python scripts/download.py --repo_id openlm-research/open_llama_7b_700bt_preview --local_dir checkpoints/open-llama/7B
``
and then attempting to convert them with:
`python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B `

I receive the following error (python 3.11, ubuntu)
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/data/malek/malekRD/lit-llama/scripts/convert_hf_checkpoint.py", line 136, in <module>
    CLI(convert_hf_checkpoint)
  File "/home/malek/.local/lib/python3.11/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/malek/.local/lib/python3.11/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/home/malek/miniconda3/envs/llama/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/malek/malekRD/lit-llama/scripts/convert_hf_checkpoint.py", line 109, in convert_hf_checkpoint
    torch.save(model.state_dict(), output_dir / "lit-llama.pth")
  File "/home/malek/miniconda3/envs/llama/lib/python3.11/site-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/malek/miniconda3/envs/llama/lib/python3.11/site-packages/torch/serialization.py", line 291, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 24793583104 vs 24793583000
```

I tried reinstalling/torch dependencies with no luck, anyone else run into this issue when converting openLLaMa weights from the hub?

**Comment by lantiga** [comment]
Can you post your current environment with `pip freeze` and do you have space left on your device when you are writing?

**Comment by momalekabid** [comment]
issue seems to be have resolved after i cleared up some disk space + tried again after the latest commit (supporting lazy loading). thanks.
