### ISSUE TITLE
[When loading fine-tuned LLaMa-Adapter] RuntimeError: shape '[1, 1, 1, 1]' is invalid for input of size 32

### ISSUE THREAD

**Issue by JulianBvW** [Lightning-AI/lit-llama#355]
After succesfully (= run without errors and generated `lit-llama-adapter-finetuned.pth`) fine-tuning LLaMa-Adapter using the alpaca json data, I get an error when trying to run `generate/adapter.py`.

Terminal output:

```
(llama_adapter) jwuelfingen@raider:~/Projects/Llama/lit-llama$ py generate/adapter.py --prompt "Recommend a movie to watch on the weekend."

Loading model ...

Traceback (most recent call last):
  File "generate/adapter.py", line 108, in <module>
    CLI(main)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "generate/adapter.py", line 71, in main
    model.load_state_dict(adapter_checkpoint, strict=False)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 1 more time]
  File "/homes/jwuelfingen/anaconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2009, in load
    module._load_from_state_dict(
  File "/homes/jwuelfingen/Projects/Llama/lit-llama/lit_llama/adapter.py", line 121, in _load_from_state_dict
    state_dict[name] = tensor.reshape(1, 1, 1, 1).repeat(1, self.n_head, 1, 1)
RuntimeError: shape '[1, 1, 1, 1]' is invalid for input of size 32
```

I hope someone can help me with that.

**Comment by carmocca** [comment]
This was fixed with https://github.com/Lightning-AI/lit-llama/pull/348. Can you try pulling master?
