### ISSUE TITLE
FSDPStrategy fails with multiple GPUs

### ISSUE THREAD

**Issue by HeorhiiS** [Lightning-AI/lit-llama#361]
I have been trying to finetune LLAMA, that on 7B size and 8 v100 GPUs takes longer than a day on the original `lora.py` script, this seemed wrong as training time of few hours often is seen. To remedy this I decided to use FSDP to increase the minibatch size and speed up the training. :
```python
    auto_wrap_policy = partial(transformer_auto_wrap_policy, transformer_layer_cls={Block})

    strategy = FSDPStrategy(auto_wrap_policy=auto_wrap_policy, activation_checkpointing=Block)

    #  Initialize Fabric 

    # setting for 4 GPUs with bf16 mixed precision and FSDP distributed training strategy

    fabric = L.Fabric(accelerator="cuda", devices=4, precision="bf16-mixed", strategy=strategy)

    fabric.launch()
```

Upon trying the `FSDPStrategy() `just as in the example of lit-llama docs above I get an error:

```
Traceback (most recent call last):
  File "/llamafb/llama/lit-llama/finetune/lora.py", line 243, in <module>
    CLI(main)
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/llamafb/llama/lit-llama/finetune/lora.py", line 101, in main
    model, optimizer = fabric.setup(model, optimizer)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/lightning/fabric/fabric.py", line 212, in setup
    module, optimizers = self._strategy.setup_module_and_optimizers(  # type: ignore[assignment]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/lightning/fabric/strategies/fsdp.py", line 198, in setup_module_and_optimizers
    module = self.setup_module(module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/lightning/fabric/strategies/fsdp.py", line 211, in setup_module
    wrapped_module = FullyShardedDataParallel(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 408, in __init__
    _init_param_handle_from_module(
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/torch/distributed/fsdp/_init_utils.py", line 429, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/torch/distributed/fsdp/_init_utils.py", line 525, in _init_param_handle_from_params
    handle = FlatParamHandle(
             ^^^^^^^^^^^^^^^^
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/torch/distributed/fsdp/flat_param.py", line 366, in __init__
    self._init_flat_param(params, fully_sharded_module, use_orig_params)
  File "/conda-envs/llamaenv/lib/python3.11/site-packages/torch/distributed/fsdp/flat_param.py", line 440, in _init_flat_param
    raise ValueError(
ValueError: `FlatParameter` requires uniform `requires_grad`
```

**Comment by HeorhiiS** [comment]
Closing because I found the fix.

**Comment by ForcewithMe66** [comment]
I also faced this problem while I tried to tine-tune lora on multiple GPUs with FSDP.
