### ISSUE TITLE
KeyError: 'Wizard-Vicuna-13B-Uncensored-HF' when converting the checkpoint

### ISSUE THREAD

**Issue by flotos** [Lightning-AI/lit-llama#399]
Hi, I have downloaded wizard vicuna using `python scripts/download.py --repo_id TheBloke/Wizard-Vicuna-13B-Uncensored-HF`

After that, I ran `python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/TheBloke/Wizard-Vicuna-13B-Uncensored-HF` and run into this error:

```
Traceback (most recent call last):
  File "/workspace/Lit-Parrot/scripts/convert_hf_checkpoint.py", line 164, in <module>
    CLI(convert_hf_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/Lit-Parrot/scripts/convert_hf_checkpoint.py", line 124, in convert_hf_checkpoint
    config = Config.from_name(model_name)
  File "/workspace/Lit-Parrot/lit_parrot/config.py", line 59, in from_name
    conf_dict = configs[name].copy()
KeyError: 'Wizard-Vicuna-13B-Uncensored-HF'
```

Any idea if I do something wrong ? Is this repo limited to the ones specified in the readme docs and not any llama based model ? Thanks. I had no issues using the same steps for Falcon.

**Comment by carmocca** [comment]
> Is this repo limited to the ones specified in the readme docs and not any llama based model ?

Correct. I transferred your issue to https://github.com/Lightning-AI/lit-llama, which is the same but for LlaMA based checkpoints

However, Vicuna is not supported at the moment (duplicates: https://github.com/Lightning-AI/lit-llama/issues/377, https://github.com/Lightning-AI/lit-llama/issues/366)
