### ISSUE TITLE
Adapter finetuning OOM error

### ISSUE THREAD

**Issue by wasifferoze** [Lightning-AI/lit-llama#402]
I get this OOM error on 24GB memory. I have tried different micro_batch_size till 1. Still I get this error. I have tried multiple devices too but still same error. What could be the reason. 
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.65 GiB total capacity; 13.07 GiB already allocated; 7.31 MiB free; 13.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

full traceback

`Global seed set to 1337
Number of trainable parameters: 1229760
Traceback (most recent call last):
  File "finetune/adapter.py", line 263, in <module>
    CLI(main)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "finetune/adapter.py", line 104, in main
    train(fabric, model, optimizer, train_data, val_data, out_dir)
  File "finetune/adapter.py", line 136, in train
    logits = model(input_ids)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/disk/NLP/WF/lit-llama-main/lit_llama/adapter.py", line 282, in forward
    x, *_ = block(x, rope, mask, max_seq_length)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/disk/NLP/WF/lit-llama-main/lit_llama/adapter.py", line 212, in forward
    h, new_kv_cache, new_adapter_kv_cache = self.attn(
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/disk/NLP/WF/lit-llama-main/lit_llama/adapter.py", line 108, in forward
    q, k, v = self.c_attn(x).split(self.n_embd, dim=2) # (B, T, 3 * C) --> 3 * (B, T, C)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/anaconda3/envs/pytorch2/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.65 GiB total capacity; 13.07 GiB already allocated; 7.31 MiB free; 13.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by richardsun-voyager** [comment]
Probably 24G is too small. I loaded the model with the  huggingface API, in a bf16 precision. It cost approx 25G in memory.
Finetuning with lit-llama costs almost 40g on my server.

**Comment by wasifferoze** [comment]
In guide, it say we can fine-tune on 25G gpu. I also tried multiple GPUs I get same error.

**Comment by aniketmaurya** [comment]
hi @wasifferoze, were you able to solve this issue? We have a tutorial here on [how to avoid OOM](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md)

**Comment by piotrbazan** [comment]
Thanks @aniketmaurya, had the same issue. After setting `micro_batch_size = 1` I was able to run finetuning lora on llama 2.

**Comment by aniketmaurya** [comment]
@carmocca I guess we can close this issue.
