### ISSUE TITLE
Issue with "kv_cache" while using modified generate/lora.py for a list of inputs

### ISSUE THREAD

**Issue by mriganktiwari** [Lightning-AI/lit-llama#418]
Dimensions of (k,v) are getting changed due to **kv_cache** somewhere between line 195-228 in file [model.py](https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/model.py).

This is happening when [line 65](https://github.com/Lightning-AI/lit-llama/blob/03f5d5e597c82507960baaefb132cbcc4847f317/generate.py#L65) is called by [this generate function call](https://github.com/Lightning-AI/lit-llama/blob/03f5d5e597c82507960baaefb132cbcc4847f317/generate/lora.py#L90)

> This ```generate``` function call I've put under a ```for``` loop to iterate over a list of inputs for generation using LoRA weights.

Am trying to find how can I reset this [kv_cache](https://github.com/Lightning-AI/lit-llama/blob/03f5d5e597c82507960baaefb132cbcc4847f317/lit_llama/model.py#L66), as soon as new input is taken. Any help is appreciated.

More error logs:
```
Traceback (most recent call last):
  File "generate/lora_itn.py", line 130, in <module>
    CLI(main)
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/opt/conda/lib/python3.8/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "generate/lora_itn.py", line 96, in main
    output = generate(model,
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/mrigank-llm-datavol-1/lit-llama/generate.py", line 71, in generate
    logits = model(x, max_seq_length, input_pos)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    output = self._forward_module(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/mrigank-llm-datavol-1/lit-llama/lit_llama/model.py", line 114, in forward
    x, self.kv_caches[i] = block(x, rope, mask, max_seq_length, input_pos, self.kv_caches[i])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/mrigank-llm-datavol-1/lit-llama/lit_llama/model.py", line 163, in forward
    h, new_kv_cache = self.attn(self.rms_1(x), rope, mask, max_seq_length, input_pos, kv_cache)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/mrigank-llm-datavol-1/lit-llama/lit_llama/model.py", line 230, in forward
    y = F.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0)
RuntimeError: The size of tensor a (318) must match the size of tensor b (314) at non-singleton dimension 3
```

file **lora_itn.py**  is a modified **lora.py** with changes for taking in a list of inputs instead.

**Comment by carmocca** [comment]
You can `reset_cache` after generation. Lit-GPT does it: https://github.com/Lightning-AI/lit-gpt/blob/main/generate/base.py#L180

**Comment by SagiPolaczek** [comment]
I got into the same issue too. As @carmocca mentioned, I also solved it using `reset_cache()`.

With that being said, I don't fully understand the purpose and the usage of this cache mechanism. Could someone please explain it briefly or refer to an updated source? Why do we need that? And why do we need to reset it when doing an inference for two consecutive different inputs?


Thanks!

**Comment by carmocca** [comment]
You can read about the KV cache here: https://kipp.ly/transformer-inference-arithmetic/

It depends on the sequence length, so if it changes it needs to be reset.

When you do inference with a prompt for a maximum number of tokens, since we know what the maximum sequence length will be, we set it to that value.
But if the next generation length is different, it needs to be reset.
You could also set it to a value that is equal to the longest of your generation, but it would be wasteful for the generations that are smaller than that.

**Comment by SagiPolaczek** [comment]
@carmocca thanks for the quick reply and your awesome work! ⚡

**Comment by HenryPengZou** [comment]
When doing inference for multiple consecutive inference on a LoRA fine-tuned LLaMA, I found that when use 'reset_cache' after inference  will affect the performance of inference on the next input. However, if you load the model again after each generation, the performance stays good. But reloading consumes lots of time. Could you help provide some explanation why 'reset_cache' will decrease the performance of the inference on the next consecutive inputs?
