### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by Vinter8848** [Lightning-AI/lit-llama#445]
Loading model ...
Traceback (most recent call last):
  File "/home/Zhengwt/lit-llama/evaluate/lora.py", line 172, in <module>
    CLI(main)
  File "/home/Zhengwt/anaconda3/envs/lit-llama/lib/python3.9/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/Zhengwt/anaconda3/envs/lit-llama/lib/python3.9/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/Zhengwt/lit-llama/evaluate/lora.py", line 105, in main
    model = LLaMA.from_name(name)
  File "/home/Zhengwt/lit-llama/lit_llama/model.py", line 124, in from_name
    return cls(LLaMAConfig.from_name(name))
  File "/home/Zhengwt/lit-llama/lit_llama/model.py", line 59, in __init__
    h=nn.ModuleList(Block(config) for _ in range(config.n_layer)),
  File "/home/Zhengwt/anaconda3/envs/lit-llama/lib/python3.9/site-packages/torch/nn/modules/container.py", line 279, in __init__
    self += modules
  File "/home/Zhengwt/anaconda3/envs/lit-llama/lib/python3.9/site-packages/torch/nn/modules/container.py", line 320, in __iadd__
    return self.extend(modules)
  File "/home/Zhengwt/anaconda3/envs/lit-llama/lib/python3.9/site-packages/torch/nn/modules/container.py", line 401, in extend
    for i, module in enumerate(modules):
  File "/home/Zhengwt/lit-llama/lit_llama/model.py", line 59, in <genexpr>
    h=nn.ModuleList(Block(config) for _ in range(config.n_layer)),
  File "/home/Zhengwt/lit-llama/lit_llama/model.py", line 150, in __init__
    self.attn = CausalSelfAttention(config)
  File "/home/Zhengwt/lit-llama/lit_llama/lora.py", line 428, in __init__
    self.c_attn = MergedLinear(
  File "/home/Zhengwt/lit-llama/lit_llama/lora.py", line 134, in __init__
    nn.Linear.__init__(self, in_features, out_features, **kwargs)
  File "/home/Zhengwt/lit-llama/lit_llama/quantization.py", line 45, in __init__
    super().__init__(*args, **kwargs, has_fp16_weights=False, threshold=6.0)
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by Vinter8848** [comment]
I encountered the above problem when executing this command.
```python
python evaluate/lora.py --quantize llm.int8
```

**Comment by Vinter8848** [comment]
Can you provide some ideas to help me solve this problem? If you can, I would be extremely grateful.

**Comment by carmocca** [comment]
This has been fixed in lit-gpt: https://github.com/Lightning-AI/lit-gpt
