### ISSUE TITLE
ValueError: Precision 'bf16-true' is invalid

### ISSUE THREAD

**Issue by AlphaGoMK** [Lightning-AI/lit-llama#447]
I got ValueError when running `python finetune/lora.py`  
```
Traceback (most recent call last):
  File "/data/llm/lit-llama/finetune/lora.py", line 218, in <module>
    CLI(main)
  File "/home/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/.local/lib/python3.9/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/data/llm/lit-llama/finetune/lora.py", line 55, in main
    fabric = L.Fabric(accelerator="cuda", devices=1, precision="bf16-true") # fixme bf16-true
  File "/home/.local/lib/python3.9/site-packages/lightning/fabric/fabric.py", line 89, in __init__
    self._connector = _Connector(
  File "/home/.local/lib/python3.9/site-packages/lightning/fabric/connector.py", line 126, in __init__
    self._check_config_and_set_final_flags(
  File "/home/.local/lib/python3.9/site-packages/lightning/fabric/connector.py", line 208, in _check_config_and_set_final_flags
    raise ValueError(f"Precision {repr(precision)} is invalid. Allowed precision values: {supported_precision}")
ValueError: Precision 'bf16-true' is invalid. Allowed precision values: ('64', '32', '16', 'bf16', 64, 32, 16)
```
Looks like default version of `lightning==2.0.6` in pypi caused such error.  

Comparing the code in [2.0.6](https://github.com/Lightning-AI/lightning/blob/ecffb2aa0cc430ddeb87d776ba51112cca87d4db/src/lightning/fabric/plugins/precision/precision.py#L26) with [master commit](https://github.com/Lightning-AI/lightning/blob/c95dbac2e87cbe3ac8575e40f7baf62e81d84859/src/lightning/fabric/plugins/precision/precision.py#L26), lacking of `"16-true"` caused the value error. 

Problem solved after install lightning from github.
1. `git clone git@github.com:Lightning-AI/lightning.git` 
2. `cd lightning && pip install . `

**Comment by rasbt** [comment]
Sorry about the trouble and good suggestion. In practice, I recommend installing fit via the `requirements.txt`

```
pip install requirements.txt --upgrade
```

which uses the suggested installation from GitHub
<img width="551" alt="Screenshot 2023-08-13 at 10 33 13 AM" src="https://github.com/Lightning-AI/lit-llama/assets/5618407/2ea4d329-6ad6-428c-941c-961c77d09e71">
