### ISSUE TITLE
Mistral Model

### ISSUE THREAD

**Issue by PierreColombo** [Lightning-AI/lit-llama#458]
Hello !
Is there any plan to incorporate Mistral ai Model?
Cheers,

**Comment by lantiga** [comment]
Hey, lit-GPT supports it https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_mistral.md
with capped context length (which should be enough for most practical uses right now)

**Comment by UYousafzai** [comment]
### Issue
Converting the Mistral Model fails on convert

### Link to the Mistral Specific Model
https://huggingface.co/Arc53/docsgpt-7b-mistral

### Stack Trace on Conversion Fail

python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/docgpt/ --output_dir checkpoints/lit-l
lama-2 --model_size 7B
Initializing lit-llama
Saving to disk at checkpoints/lit-llama-2
Processing checkpoints/docgpt/pytorch_model-00001-of-00003.bin
Traceback (most recent call last):
  File "scripts/convert_hf_checkpoint.py", line 166, in <module>
    CLI(convert_hf_checkpoint)
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/umar/miniconda3/envs/llama2-production/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "scripts/convert_hf_checkpoint.py", line 133, in convert_hf_checkpoint
    sd_key = weight_map[name]
KeyError: 'embed_tokens.weight'
