### ISSUE TITLE
error when run  [python3 generate.py --quantize true ]: undefined symbol: cget_col_row_stats 

### ISSUE THREAD

**Issue by alexhmyang** [Lightning-AI/lit-llama#66]
u20@u20:~/lit-llama$ python3 generate.py --quantize true --prompt "Hello, my name is"
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/home/u20/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Loading model ...
Traceback (most recent call last):
  File "generate.py", line 147, in <module>
    CLI(main)
  File "/home/u20/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/home/u20/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "generate.py", line 108, in main
    model = LLaMA.from_name(model_size)
  File "/home/u20/lit-llama/lit_llama/model.py", line 223, in from_name
    return cls(LLaMAConfig.from_name(name))
  File "/home/u20/lit-llama/lit_llama/model.py", line 179, in __init__
    self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)
  File "/home/u20/lit-llama/lit_llama/quantization.py", line 31, in __init__
    self._quantize_weight(self.weight.data)
  File "/home/u20/lit-llama/lit_llama/quantization.py", line 48, in _quantize_weight
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "/home/u20/.local/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1616, in double_quant
    row_stats, col_stats, nnz_row_ptr = get_colrow_absmax(
  File "/home/u20/.local/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1505, in get_colrow_absmax
    lib.cget_col_row_stats(ptrA, ptrRowStats, ptrColStats, ptrNnzrows, ct.c_float(threshold), rows, cols)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/u20/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats

**Comment by lantiga** [comment]
Can you run
```
pip freeze | grep -E 'sentencepiece|bitsandbytes|torch'
```
on your system? We haven't pinned those but we should, I'd like to understand what versions are you running.

My versions are:
```
bitsandbytes==0.37.2
sentencepiece==0.1.97
torch==2.0.0
```

**Comment by alexhmyang** [comment]
$ pip freeze | grep -E 'sentencepiece|bitsandbytes|torch'

bitsandbytes==0.37.2
pytorch-lightning==2.0.1
sentencepiece==0.1.97
torch==2.0.0
torchaudio==0.13.1+cu116
torchmetrics==0.11.4
torchvision==0.14.1+cu116

**Comment by alexhmyang** [comment]
> Can you run
> 
> ```
> pip freeze | grep -E 'sentencepiece|bitsandbytes|torch'
> ```
> 
> on your system? We haven't pinned those but we should, I'd like to understand what versions are you running.
> 
> My versions are:
> 
> ```
> bitsandbytes==0.37.2
> sentencepiece==0.1.97
> torch==2.0.0
> ```
i found the solution, is here 
https://github.com/TimDettmers/bitsandbytes/issues/156#issuecomment-1462329713

**Comment by carmocca** [comment]
Glad you found the issue! Closing
