### ISSUE TITLE
AttributeError: module 'lightning' has no attribute 'Fabric'

### ISSUE THREAD

**Issue by htcml** [Lightning-AI/lit-llama#78]
$ python generate.py --prompt "Hello, my name is"

```
Traceback (most recent call last):
  File "generate.py", line 148, in <module>
    CLI(main)
  File "/axp/aida/data/platformds/aiservices/conda/envs/llama/lib/python3.7/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/axp/aida/data/platformds/aiservices/conda/envs/llama/lib/python3.7/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "generate.py", line 104, in main
    fabric = L.Fabric(accelerator=accelerator, devices=1)
AttributeError: module 'lightning' has no attribute 'Fabric'
```

**Comment by awaelchli** [comment]
Hey @htcml 
For this repo you need lightning version 2.0. 

To run this repo, you need to 
```py
pip install -r requirements.txt
```

**Comment by awaelchli** [comment]
@htcml Did you see my reply? Did you manage to install the right versions?

**Comment by lantiga** [comment]
Closing, feel free to reopen @htcml
